# Generated by Django 4.1.7 on 2023-03-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
