# Generated by Django 4.1.7 on 2023-04-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_options_alter_product_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='announcement',
            field=models.CharField(default=True, max_length=100, verbose_name='Краткое описание продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
