# Generated by Django 4.1.7 on 2023-04-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_announcement_product_price_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='announcement',
            field=models.CharField(default='', max_length=100, verbose_name='Краткое описание продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='Цена'),
        ),
    ]
