# Generated by Django 4.1.7 on 2023-04-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='announcement',
            field=models.CharField(default=False, max_length=100, verbose_name='Краткое описание продукта'),
        ),
    ]
