# Generated by Django 4.1.7 on 2023-04-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='announcement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое описание продукта'),
        ),
    ]
